// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBlRClnDHxB-uE6yB77ujhSEP4OdqUcto',
    appId: '1:535134078101:web:d0cf71bc6dfef1b10b079c',
    messagingSenderId: '535134078101',
    projectId: 'flutter-x-extension',
    authDomain: 'flutter-x-extension.firebaseapp.com',
    storageBucket: 'flutter-x-extension.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIKoBvn2mZ1sabEknZKeg5cr3yCqjW7yI',
    appId: '1:535134078101:android:dca648fb77a849f30b079c',
    messagingSenderId: '535134078101',
    projectId: 'flutter-x-extension',
    storageBucket: 'flutter-x-extension.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDn3ihnyUk1P2P4f0AYDtWQB7xaoh26bo',
    appId: '1:535134078101:ios:8c62d9a91bf81ab20b079c',
    messagingSenderId: '535134078101',
    projectId: 'flutter-x-extension',
    storageBucket: 'flutter-x-extension.appspot.com',
    iosClientId: '535134078101-p3vdv0s65atca6fqo5dj19ntc3kkjabc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterx',
  );
}
